//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVIT_EF_NhanVien.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HVIT_EF_NhanVien.Helper.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia chi khong hop le!.
        /// </summary>
        internal static string errorDiaChi {
            get {
                return ResourceManager.GetString("errorDiaChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id nhap vao phai la so nguyen!.
        /// </summary>
        internal static string errorDuAnId {
            get {
                return ResourceManager.GetString("errorDuAnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email khong hop le!.
        /// </summary>
        internal static string errorEmail {
            get {
                return ResourceManager.GetString("errorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He so luong khong hop le!.
        /// </summary>
        internal static string errorHeSoLuong {
            get {
                return ResourceManager.GetString("errorHeSoLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten khong duoc qua 20 ky tu va co it nhat 2 tu!.
        /// </summary>
        internal static string errorHoTen {
            get {
                return ResourceManager.GetString("errorHoTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id nhap vao phai la so nguyen!.
        /// </summary>
        internal static string errorNhanVienId {
            get {
                return ResourceManager.GetString("errorNhanVienId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So dien thoai khong hop le!.
        /// </summary>
        internal static string errorSDT {
            get {
                return ResourceManager.GetString("errorSDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So gio lam phai la so nguyen duong!.
        /// </summary>
        internal static string errorSoGioLam {
            get {
                return ResourceManager.GetString("errorSoGioLam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia chi: .
        /// </summary>
        internal static string inputDiaChi {
            get {
                return ResourceManager.GetString("inputDiaChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma du an: .
        /// </summary>
        internal static string inputDuAnId {
            get {
                return ResourceManager.GetString("inputDuAnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: .
        /// </summary>
        internal static string inputEmail {
            get {
                return ResourceManager.GetString("inputEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  He so luong: .
        /// </summary>
        internal static string inputHeSoLuong {
            get {
                return ResourceManager.GetString("inputHeSoLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ho ten: .
        /// </summary>
        internal static string inputHoTen {
            get {
                return ResourceManager.GetString("inputHoTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma nhan vien: .
        /// </summary>
        internal static string inputNhanVienId {
            get {
                return ResourceManager.GetString("inputNhanVienId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So dien thoai: .
        /// </summary>
        internal static string inputSDT {
            get {
                return ResourceManager.GetString("inputSDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So gio lam: .
        /// </summary>
        internal static string inputSoGioLam {
            get {
                return ResourceManager.GetString("inputSoGioLam", resourceCulture);
            }
        }
    }
}
