//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muc1_7 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Muc1_7.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban can nhap so nguyen trong khoang tu 0 - 23.
        /// </summary>
        internal static string ErrNhapGio {
            get {
                return ResourceManager.GetString("ErrNhapGio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban can nhap so nguyen trong khoang tu 0 - 59.
        /// </summary>
        internal static string ErrNhapPhutGiay {
            get {
                return ResourceManager.GetString("ErrNhapPhutGiay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap giay: .
        /// </summary>
        internal static string StrNhapGiay {
            get {
                return ResourceManager.GetString("StrNhapGiay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap gio: .
        /// </summary>
        internal static string StrNhapGio {
            get {
                return ResourceManager.GetString("StrNhapGio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap phut: .
        /// </summary>
        internal static string StrNhapPhut {
            get {
                return ResourceManager.GetString("StrNhapPhut", resourceCulture);
            }
        }
    }
}
