//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVIT_EF_QLHocSinh.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HVIT_EF_QLHocSinh.Helper.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma hoc sinh phai la so nguyen!.
        /// </summary>
        internal static string errorHocSinhId {
            get {
                return ResourceManager.GetString("errorHocSinhId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ho ten khong duoc qua 20 ky tu va phai co it nhat 2 tu!.
        /// </summary>
        internal static string errorHoTen {
            get {
                return ResourceManager.GetString("errorHoTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma lop phai la so nguyen!.
        /// </summary>
        internal static string errorLopId {
            get {
                return ResourceManager.GetString("errorLopId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngay sinh phai nam trong khoang tu 2001 - 2013!.
        /// </summary>
        internal static string errorNgaySinh {
            get {
                return ResourceManager.GetString("errorNgaySinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Que quan nhap khong hop le!.
        /// </summary>
        internal static string errorQueQuan {
            get {
                return ResourceManager.GetString("errorQueQuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ma ho sinh: .
        /// </summary>
        internal static string inputHocSinhId {
            get {
                return ResourceManager.GetString("inputHocSinhId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ho ten: .
        /// </summary>
        internal static string inputHoTen {
            get {
                return ResourceManager.GetString("inputHoTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ma lop: .
        /// </summary>
        internal static string inputLopId {
            get {
                return ResourceManager.GetString("inputLopId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ngay sinh: .
        /// </summary>
        internal static string inputNgaySinh {
            get {
                return ResourceManager.GetString("inputNgaySinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap que quan: .
        /// </summary>
        internal static string inputQueQuan {
            get {
                return ResourceManager.GetString("inputQueQuan", resourceCulture);
            }
        }
    }
}
