// <auto-generated />
using System;
using HVITQuanLyNhanVien;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HVITQuanLyNhanVien.Migrations
{
    [DbContext(typeof(QuanLyNhanVienDbContext))]
    [Migration("20200721112957_QLNV")]
    partial class QLNV
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HVITQuanLyNhanVien.Entities.DuAn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhanCongId")
                        .HasColumnType("int");

                    b.Property<string>("TenDuAn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PhanCongId");

                    b.ToTable("DuAn");
                });

            modelBuilder.Entity("HVITQuanLyNhanVien.Entities.NhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("HeSoLuong")
                        .HasColumnType("float");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhanCongId")
                        .HasColumnType("int");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PhanCongId");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("HVITQuanLyNhanVien.Entities.PhanCong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DuAnId")
                        .HasColumnType("int");

                    b.Property<int?>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<int?>("SoGioLam")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PhanCong");
                });

            modelBuilder.Entity("HVITQuanLyNhanVien.Entities.DuAn", b =>
                {
                    b.HasOne("HVITQuanLyNhanVien.Entities.PhanCong", "PhanCong")
                        .WithMany("DuAns")
                        .HasForeignKey("PhanCongId");
                });

            modelBuilder.Entity("HVITQuanLyNhanVien.Entities.NhanVien", b =>
                {
                    b.HasOne("HVITQuanLyNhanVien.Entities.PhanCong", "PhanCong")
                        .WithMany("NhanViens")
                        .HasForeignKey("PhanCongId");
                });
#pragma warning restore 612, 618
        }
    }
}
