//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVIT_MVC_DonDatHang.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HVIT_MVC_DonDatHang.Helper.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gia ban phai la so thuc!.
        /// </summary>
        internal static string errorGiaBan {
            get {
                return ResourceManager.GetString("errorGiaBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID phai la so nguyen!.
        /// </summary>
        internal static string errorId {
            get {
                return ResourceManager.GetString("errorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma don dat hang phai la so nguyen!.
        /// </summary>
        internal static string errorMaDDH {
            get {
                return ResourceManager.GetString("errorMaDDH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma san pham phai la so nguyen!.
        /// </summary>
        internal static string errorMaSP {
            get {
                return ResourceManager.GetString("errorMaSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngay tao khong hop le!.
        /// </summary>
        internal static string errorNgayTao {
            get {
                return ResourceManager.GetString("errorNgayTao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So hieu don khong hop le!.
        /// </summary>
        internal static string errorSoHieuDon {
            get {
                return ResourceManager.GetString("errorSoHieuDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So luong nhap vao phai la so nguyen!.
        /// </summary>
        internal static string errorSoLuong {
            get {
                return ResourceManager.GetString("errorSoLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten san pham khong hop le!.
        /// </summary>
        internal static string errorTenSP {
            get {
                return ResourceManager.GetString("errorTenSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap gia ban: .
        /// </summary>
        internal static string inputGiaBan {
            get {
                return ResourceManager.GetString("inputGiaBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID: .
        /// </summary>
        internal static string inputId {
            get {
                return ResourceManager.GetString("inputId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma don dat hang: .
        /// </summary>
        internal static string inputMaDDH {
            get {
                return ResourceManager.GetString("inputMaDDH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma san pham: .
        /// </summary>
        internal static string inputMaSP {
            get {
                return ResourceManager.GetString("inputMaSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngay tao: .
        /// </summary>
        internal static string inputNgayTao {
            get {
                return ResourceManager.GetString("inputNgayTao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So hieu don: .
        /// </summary>
        internal static string inputSoHieuDon {
            get {
                return ResourceManager.GetString("inputSoHieuDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So luong: .
        /// </summary>
        internal static string inputSoLuong {
            get {
                return ResourceManager.GetString("inputSoLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ten san pham: .
        /// </summary>
        internal static string inputTenSP {
            get {
                return ResourceManager.GetString("inputTenSP", resourceCulture);
            }
        }
    }
}
