// <auto-generated />
using System;
using HVIT_EF_QLNguyenLieu;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HVIT_EF_QLNguyenLieu.Migrations
{
    [DbContext(typeof(QLNguyenLieuDbContext))]
    [Migration("20200729142108_update920_29062020")]
    partial class update920_29062020
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HVIT_EF_QLNguyenLieu.Entities.ChiTietPhieuThu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NguyenLieuId")
                        .HasColumnType("int");

                    b.Property<int?>("PhieuThuId")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongBan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NguyenLieuId");

                    b.HasIndex("PhieuThuId");

                    b.ToTable("ChiTietPhieuThus");
                });

            modelBuilder.Entity("HVIT_EF_QLNguyenLieu.Entities.LoaiNguyenLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoaiNguyenLieus");
                });

            modelBuilder.Entity("HVIT_EF_QLNguyenLieu.Entities.NguyenLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DonViTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("GiaBan")
                        .HasColumnType("float");

                    b.Property<int?>("LoaiNguyenLieuId")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongKho")
                        .HasColumnType("int");

                    b.Property<string>("TenNguyenLieu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoaiNguyenLieuId");

                    b.ToTable("NguyenLieus");
                });

            modelBuilder.Entity("HVIT_EF_QLNguyenLieu.Entities.PhieuThu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanVienLap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ThanhTien")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PhieuThus");
                });

            modelBuilder.Entity("HVIT_EF_QLNguyenLieu.Entities.RecycleBin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NguyenLieuId")
                        .HasColumnType("int");

                    b.Property<int?>("PhieuThuId")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongBan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RecycleBins");
                });

            modelBuilder.Entity("HVIT_EF_QLNguyenLieu.Entities.ChiTietPhieuThu", b =>
                {
                    b.HasOne("HVIT_EF_QLNguyenLieu.Entities.NguyenLieu", "NguyenLieu")
                        .WithMany("ChiTietPhieuThus")
                        .HasForeignKey("NguyenLieuId");

                    b.HasOne("HVIT_EF_QLNguyenLieu.Entities.PhieuThu", "PhieuThu")
                        .WithMany("ChiTietPhieuThus")
                        .HasForeignKey("PhieuThuId");
                });

            modelBuilder.Entity("HVIT_EF_QLNguyenLieu.Entities.NguyenLieu", b =>
                {
                    b.HasOne("HVIT_EF_QLNguyenLieu.Entities.LoaiNguyenLieu", "LoaiNguyenLieu")
                        .WithMany("NguyenLieus")
                        .HasForeignKey("LoaiNguyenLieuId");
                });
#pragma warning restore 612, 618
        }
    }
}
