//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVIT_EF_QLNgayHoc.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HVIT_EF_QLNgayHoc.Helper.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ho ten khong duoc qua 20 ky tu va phai co it nhat 2 tu!.
        /// </summary>
        internal static string errorHoTen {
            get {
                return ResourceManager.GetString("errorHoTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma hoc vien khong hop le!.
        /// </summary>
        internal static string errorMaHocVien {
            get {
                return ResourceManager.GetString("errorMaHocVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma khoa hoc khong hop le!.
        /// </summary>
        internal static string errorMaKhoaHoc {
            get {
                return ResourceManager.GetString("errorMaKhoaHoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam nhap vao khong hop le!.
        /// </summary>
        internal static string errorNam {
            get {
                return ResourceManager.GetString("errorNam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngay sinh khong hop le!.
        /// </summary>
        internal static string errorNgaySinh {
            get {
                return ResourceManager.GetString("errorNgaySinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So dien thoai khong hop le!.
        /// </summary>
        internal static string errorSDT {
            get {
                return ResourceManager.GetString("errorSDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thang nhap vao khong hop le!.
        /// </summary>
        internal static string errorThang {
            get {
                return ResourceManager.GetString("errorThang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ho ten: .
        /// </summary>
        internal static string inputHoTen {
            get {
                return ResourceManager.GetString("inputHoTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma hoc vien: .
        /// </summary>
        internal static string inputMaHocVien {
            get {
                return ResourceManager.GetString("inputMaHocVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma khoa hoc: .
        /// </summary>
        internal static string inputMaKhoaHoc {
            get {
                return ResourceManager.GetString("inputMaKhoaHoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap nam: .
        /// </summary>
        internal static string inputNam {
            get {
                return ResourceManager.GetString("inputNam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngay sinh: .
        /// </summary>
        internal static string inputNgaySinh {
            get {
                return ResourceManager.GetString("inputNgaySinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So dien thoai: .
        /// </summary>
        internal static string inputSDT {
            get {
                return ResourceManager.GetString("inputSDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap thang: .
        /// </summary>
        internal static string inputThang {
            get {
                return ResourceManager.GetString("inputThang", resourceCulture);
            }
        }
    }
}
