//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVIT_MVC_SanPham.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HVIT_MVC_SanPham.Helper.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loai san pham nhap vao phai la so nguyen!.
        /// </summary>
        internal static string errorLoaiSP {
            get {
                return ResourceManager.GetString("errorLoaiSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma san pham nhap vao phai la so nguyen!.
        /// </summary>
        internal static string errorMaSP {
            get {
                return ResourceManager.GetString("errorMaSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nha cung cap nhap vao phai la so nguyen!.
        /// </summary>
        internal static string errorNhaCC {
            get {
                return ResourceManager.GetString("errorNhaCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So dien thoai khong hop le!.
        /// </summary>
        internal static string errorSoDT {
            get {
                return ResourceManager.GetString("errorSoDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten loai khong hop le!.
        /// </summary>
        internal static string errorTenLoai {
            get {
                return ResourceManager.GetString("errorTenLoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten nha cung cap khong hop le!.
        /// </summary>
        internal static string errorTenNCC {
            get {
                return ResourceManager.GetString("errorTenNCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten san pham khong hop le!.
        /// </summary>
        internal static string errorTenSP {
            get {
                return ResourceManager.GetString("errorTenSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma loai san pham: .
        /// </summary>
        internal static string inputLoaiSP {
            get {
                return ResourceManager.GetString("inputLoaiSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ma san pham: .
        /// </summary>
        internal static string inputMaSP {
            get {
                return ResourceManager.GetString("inputMaSP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma nha cung cap: .
        /// </summary>
        internal static string inputNhaCC {
            get {
                return ResourceManager.GetString("inputNhaCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap so dien thoai: .
        /// </summary>
        internal static string inputSoDT {
            get {
                return ResourceManager.GetString("inputSoDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten loai: .
        /// </summary>
        internal static string inputTenLoai {
            get {
                return ResourceManager.GetString("inputTenLoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten nha cung cap: .
        /// </summary>
        internal static string inputTenNCC {
            get {
                return ResourceManager.GetString("inputTenNCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ten san pham: .
        /// </summary>
        internal static string inputTenSP {
            get {
                return ResourceManager.GetString("inputTenSP", resourceCulture);
            }
        }
    }
}
