//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOP_NET.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OOP_NET.Helper.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gia ban phai la so nguyen!.
        /// </summary>
        internal static string errorGiaBan {
            get {
                return ResourceManager.GetString("errorGiaBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gioi thieu khong hop le!.
        /// </summary>
        internal static string errorGioiThieu {
            get {
                return ResourceManager.GetString("errorGioiThieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyen lieu chinh khong hop le!.
        /// </summary>
        internal static string errorNguyenLieuChinh {
            get {
                return ResourceManager.GetString("errorNguyenLieuChinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten mon an qua dai hoac qua ngan!.
        /// </summary>
        internal static string errorTenMonAn {
            get {
                return ResourceManager.GetString("errorTenMonAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap gia ban: .
        /// </summary>
        internal static string inputGiaBan {
            get {
                return ResourceManager.GetString("inputGiaBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gioi thieu: .
        /// </summary>
        internal static string inputGioiThieu {
            get {
                return ResourceManager.GetString("inputGioiThieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap nguyen lieu chinh: .
        /// </summary>
        internal static string inputNguyenLieuChinh {
            get {
                return ResourceManager.GetString("inputNguyenLieuChinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ten mon an: .
        /// </summary>
        internal static string inputTenMonAn {
            get {
                return ResourceManager.GetString("inputTenMonAn", resourceCulture);
            }
        }
    }
}
