//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVIT_EF_QLNguyenLieu.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HVIT_EF_QLNguyenLieu.Helper.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don vi tinh khong qua 10 ky tu!.
        /// </summary>
        internal static string errorDonVi {
            get {
                return ResourceManager.GetString("errorDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gia ban khong hop le!.
        /// </summary>
        internal static string errorGiaBan {
            get {
                return ResourceManager.GetString("errorGiaBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma loai phai la so nguyen!.
        /// </summary>
        internal static string errorMaLoaiNL {
            get {
                return ResourceManager.GetString("errorMaLoaiNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma nguyen lieu khong hop le!.
        /// </summary>
        internal static string errorMaNguyenLieu {
            get {
                return ResourceManager.GetString("errorMaNguyenLieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma nhap phai la so nguyen!.
        /// </summary>
        internal static string errorMaPhieuThu {
            get {
                return ResourceManager.GetString("errorMaPhieuThu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngay lap khong hop le!.
        /// </summary>
        internal static string errorNgayLap {
            get {
                return ResourceManager.GetString("errorNgayLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So luong ban phai la so nguyen duong!.
        /// </summary>
        internal static string errorSoLuongBan {
            get {
                return ResourceManager.GetString("errorSoLuongBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So luong kho khong hop le!.
        /// </summary>
        internal static string errorSoLuongKho {
            get {
                return ResourceManager.GetString("errorSoLuongKho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ho ten khong hop le!.
        /// </summary>
        internal static string errorTen {
            get {
                return ResourceManager.GetString("errorTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten nguyen lieu khong qua 20 ky tu!.
        /// </summary>
        internal static string errorTenNL {
            get {
                return ResourceManager.GetString("errorTenNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don vi tinh: .
        /// </summary>
        internal static string inputDonVi {
            get {
                return ResourceManager.GetString("inputDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chu: .
        /// </summary>
        internal static string inputGhiChu {
            get {
                return ResourceManager.GetString("inputGhiChu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gia ban: .
        /// </summary>
        internal static string inputGiaBan {
            get {
                return ResourceManager.GetString("inputGiaBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma loai nguyen lieu:.
        /// </summary>
        internal static string inputMaLoaiNL {
            get {
                return ResourceManager.GetString("inputMaLoaiNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma nguyen lieu: .
        /// </summary>
        internal static string inputMaNguyenLieu {
            get {
                return ResourceManager.GetString("inputMaNguyenLieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma phieu thu: .
        /// </summary>
        internal static string inputMaPhieuThu {
            get {
                return ResourceManager.GetString("inputMaPhieuThu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngay lap:.
        /// </summary>
        internal static string inputNgayLap {
            get {
                return ResourceManager.GetString("inputNgayLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So luong ban: .
        /// </summary>
        internal static string inputSoLuongBan {
            get {
                return ResourceManager.GetString("inputSoLuongBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So luong kho: .
        /// </summary>
        internal static string inputSoLuongKho {
            get {
                return ResourceManager.GetString("inputSoLuongKho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ten: .
        /// </summary>
        internal static string inputTen {
            get {
                return ResourceManager.GetString("inputTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten nguyen lieu: .
        /// </summary>
        internal static string inputTenNL {
            get {
                return ResourceManager.GetString("inputTenNL", resourceCulture);
            }
        }
    }
}
