//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVIT_EF_QLMonAn.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HVIT_EF_QLMonAn.Helper.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cach lam khong hop le!.
        /// </summary>
        internal static string errorCachLam {
            get {
                return ResourceManager.GetString("errorCachLam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don vi khong duoc qua 10 ky tu!.
        /// </summary>
        internal static string errorDonVi {
            get {
                return ResourceManager.GetString("errorDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gia ban nhap khong hop le!.
        /// </summary>
        internal static string errorGiaBan {
            get {
                return ResourceManager.GetString("errorGiaBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gioi thieu khong hop le!.
        /// </summary>
        internal static string errorGioiThieu {
            get {
                return ResourceManager.GetString("errorGioiThieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id nhap vao phai la so nguyen!.
        /// </summary>
        internal static string errorLoaiMonAnId {
            get {
                return ResourceManager.GetString("errorLoaiMonAnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon an Id phai la so nguyen!.
        /// </summary>
        internal static string errorMonAnId {
            get {
                return ResourceManager.GetString("errorMonAnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma nguyen lieu phai la so nguyen!.
        /// </summary>
        internal static string errorNguyenLieuId {
            get {
                return ResourceManager.GetString("errorNguyenLieuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So luong nhap khong hop le!.
        /// </summary>
        internal static string errorSoLuongNL {
            get {
                return ResourceManager.GetString("errorSoLuongNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten loai khong duoc qua 20 ky tu!.
        /// </summary>
        internal static string errorTenLoai {
            get {
                return ResourceManager.GetString("errorTenLoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten mon khong hop le!.
        /// </summary>
        internal static string errorTenMon {
            get {
                return ResourceManager.GetString("errorTenMon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten nguyen lieu khong duoc qua 20 ky tu!.
        /// </summary>
        internal static string errorTenNguyenLieu {
            get {
                return ResourceManager.GetString("errorTenNguyenLieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cach lam: .
        /// </summary>
        internal static string inputCachLam {
            get {
                return ResourceManager.GetString("inputCachLam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don vi tinh: .
        /// </summary>
        internal static string inputDonVi {
            get {
                return ResourceManager.GetString("inputDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gia ban: .
        /// </summary>
        internal static string inputGiaBan {
            get {
                return ResourceManager.GetString("inputGiaBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gioi thieu: .
        /// </summary>
        internal static string inputGioiThieu {
            get {
                return ResourceManager.GetString("inputGioiThieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loai mon an Id: .
        /// </summary>
        internal static string inputLoaiMonAnId {
            get {
                return ResourceManager.GetString("inputLoaiMonAnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon an Id: .
        /// </summary>
        internal static string inputMonAnId {
            get {
                return ResourceManager.GetString("inputMonAnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma nguyen lieu: .
        /// </summary>
        internal static string inputNguyenLieuId {
            get {
                return ResourceManager.GetString("inputNguyenLieuId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So luong nguyen lieu: .
        /// </summary>
        internal static string inputSoLuongNL {
            get {
                return ResourceManager.GetString("inputSoLuongNL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten loai mon an: .
        /// </summary>
        internal static string inputTenLoai {
            get {
                return ResourceManager.GetString("inputTenLoai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten mon: .
        /// </summary>
        internal static string inputTenMon {
            get {
                return ResourceManager.GetString("inputTenMon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten nguyen lieu: .
        /// </summary>
        internal static string inputTenNguyenLieu {
            get {
                return ResourceManager.GetString("inputTenNguyenLieu", resourceCulture);
            }
        }
    }
}
