//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HVIT_MVC_HocSinh.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HVIT_MVC_HocSinh.Helper.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diem phai la so thuc nam trong khoang 0 - 10 va chia het cho 0.25.
        /// </summary>
        internal static string errorDiem {
            get {
                return ResourceManager.GetString("errorDiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma hoc sinh phai la so nguyen!.
        /// </summary>
        internal static string errorMaHS {
            get {
                return ResourceManager.GetString("errorMaHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma mon hoc phai la so nguyen!.
        /// </summary>
        internal static string errorMaMH {
            get {
                return ResourceManager.GetString("errorMaMH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngay sinh khong hop le!.
        /// </summary>
        internal static string errorNgaySinh {
            get {
                return ResourceManager.GetString("errorNgaySinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So tiet phai la so nguyen!.
        /// </summary>
        internal static string errorSoTiet {
            get {
                return ResourceManager.GetString("errorSoTiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten hoc sinh khong hop le!.
        /// </summary>
        internal static string errorTenHS {
            get {
                return ResourceManager.GetString("errorTenHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten mon hoc khong hop le!.
        /// </summary>
        internal static string errorTenMH {
            get {
                return ResourceManager.GetString("errorTenMH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap diem: .
        /// </summary>
        internal static string inputDiem {
            get {
                return ResourceManager.GetString("inputDiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ma hoc sinh: .
        /// </summary>
        internal static string inputMaHS {
            get {
                return ResourceManager.GetString("inputMaHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ma mon hoc: .
        /// </summary>
        internal static string inputMaMH {
            get {
                return ResourceManager.GetString("inputMaMH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngay sinh: .
        /// </summary>
        internal static string inputNgaySinh {
            get {
                return ResourceManager.GetString("inputNgaySinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap so tiet: .
        /// </summary>
        internal static string inputSoTiet {
            get {
                return ResourceManager.GetString("inputSoTiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ten hoc sinh: .
        /// </summary>
        internal static string inputTenHS {
            get {
                return ResourceManager.GetString("inputTenHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhap ten mon hoc: .
        /// </summary>
        internal static string inputTenMH {
            get {
                return ResourceManager.GetString("inputTenMH", resourceCulture);
            }
        }
    }
}
