// <auto-generated />
using System;
using HVIT_EF_QLNgayHoc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HVIT_EF_QLNgayHoc.Migrations
{
    [DbContext(typeof(QLKhoaHocDbContext))]
    [Migration("20200810142236_addDatabase")]
    partial class addDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HVIT_EF_QLNgayHoc.Entities.HocVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("diaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("khoaHocId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("queQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("khoaHocId");

                    b.ToTable("hocViens");
                });

            modelBuilder.Entity("HVIT_EF_QLNgayHoc.Entities.KhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("hocPhi")
                        .HasColumnType("int");

                    b.Property<string>("moTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ngayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ngayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("tenKhoaHoc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("khoaHocs");
                });

            modelBuilder.Entity("HVIT_EF_QLNgayHoc.Entities.NgayHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ghiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("khoaHocId")
                        .HasColumnType("int");

                    b.Property<string>("noiDung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("khoaHocId");

                    b.ToTable("ngayHocs");
                });

            modelBuilder.Entity("HVIT_EF_QLNgayHoc.Entities.HocVien", b =>
                {
                    b.HasOne("HVIT_EF_QLNgayHoc.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("HocViens")
                        .HasForeignKey("khoaHocId");
                });

            modelBuilder.Entity("HVIT_EF_QLNgayHoc.Entities.NgayHoc", b =>
                {
                    b.HasOne("HVIT_EF_QLNgayHoc.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("khoaHocId");
                });
#pragma warning restore 612, 618
        }
    }
}
